version: '3'

services:
  brainsoft:
    environment:
      - NODE_ENV=${NODE_ENV}
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - DATABASE_DB=${DATABASE_DB}
      - URL_DB=${URL_DB}
      - PORT_DB=${PORT_DB}
      - PORT=${PORT}
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    volumes:
      - ./node:/app/node
      - ./node_modules:/app/node_modules
    container_name: brainsoft
    ports:
      - '8080:8080'
    expose:
      - 8080
    depends_on:
      - postgres_url
    networks:
      - brainsoft

  node-installer:
    build:
      context: ./.docker
      dockerfile: Dockerfile.node-installer
    volumes:
      - ./node_modules:/node_modules
      - ./node:/node
      - ./package.json:/package.json

  postgres_url:
    image: postgres:14
    container_name: postgres_url
    environment:
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - '5432:5432'
    volumes: 
      - ./db/postgresql:/var/lib/postgresql/data
    networks:
      - brainsoft

networks:
  brainsoft:
